openapi: 3.1.0
info:
  title: Ecom API
  description: API for Logan's ecommerce project
  version: 0.1.9
paths:
  /products:
    post:
      summary: Creates a new product
      tags:
        - products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductForm'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        default:
          description: Unexpected error
  /products/{productId}:
    get:
      summary: Returns the specified product
      tags:
        - products
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: integer
          description: ID of the product to get
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        404:
          description: No product found
        default:
          description: Unexpected error
    put:
      summary: Updated the specified product
      tags:
        - products
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: integer
          description: ID of the product to get
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductForm'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        404:
          description: No product found
        default:
          description: Unexpected error
  /categories:
    get:
      summary: Returns a list of categories
      tags:
        - categories
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryList'
        404:
          description: No categories found
        default:
          description: Unexpected error
    post:
      summary: Creates a new category
      tags:
        - categories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryForm'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        default:
          description: Unexpected error
  /categories/{categoryId}:
    get:
      summary: Returns the specified category
      tags:
        - categories
      parameters:
        - in: path
          name: categoryId
          required: true
          schema:
            type: integer
          description: ID of the category to get
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        404:
          description: No category found
        default:
          description: Unexpected error
    put:
      summary: Updated the specified category
      tags:
        - categories
      parameters:
        - in: path
          name: categoryId
          required: true
          schema:
            type: integer
          description: ID of the category to get
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryForm'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        404:
          description: No product found
        default:
          description: Unexpected error
components:
  schemas:
    ProductList:
      type: Array
      items:
        $ref: '#/components/schemas/Product'
    Product:
      type: Object
      properties:
        productId:
          type: integer
        title:
          type: string
        description:
          type: string
        releaseDate:
          type: string
        categories:
          type: Array
          items:
            $ref: '#/components/schemas/Category'
    ProductForm:
      type: Object
      properties:
        title:
          type: string
        description:
          type: string
        releaseDate:
          type: string
        categories:
          type: Array
          items:
            $ref: '#/components/schemas/Category'
    CategoryList:
      type: Array
      items:
        $ref: '#/components/schemas/Category'
    Category:
      type: Object
      properties:
        categoryId:
          type: integer
        name:
          type: string
    CategoryForm:
      type: Object
      properties:
        name:
          type: string